name: KingdomCore
author: EpicSteve33
main: KingdomCore\Main
api: [2.0.0]
version: 1.5
commands:
 help:
  usage: /help
  description: Help Command
 hub:
  usage: /hub
  description: Main Hub Command
 flyon:
  usage: Hub Only Command
  description: Hub Only Command
