name: KingdomCore
author: EpicSteve33
main: KingdomCore\Main
api: [2.0.0]
version: 1.6
commands:
 help:
  usage: /help
  description: Help Command
 hub:
  usage: /hub
  description: Main Hub Command
 fly:
  usage: /flyon
  description: fly Command
